routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogOutController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Route;

Route::view('/', 'home.index')->name('home.index');
Route::redirect('/main', '/', 301);

Route::prefix('/blogs')->middleware('auth')->group(function () {
    Route::get('/', [BlogController::class, 'index'])->name('blogs.index');
    Route::get('/{blog}', [BlogController::class, 'show'])->name('blogs.show')->whereNumber('blog');
    Route::get('/categories/{category}', [BlogController::class, 'blogsByCategory'])->name('blogs.byCategory')->whereNumber('category');
    Route::get('/create', [BlogController::class, 'create'])->name('blogs.create');
    Route::post('/', [BlogController::class, 'store'])->name('blogs.store');
    Route::get('/{blog}/edit', [BlogController::class, 'edit'])->name('blogs.edit')->whereNumber('blog');
    Route::patch('/{blog}', [BlogController::class, 'update'])->name('blogs.update')->whereNumber('blog');
    Route::delete('/{blog}', [BlogController::class, 'destroy'])->name('blogs.destroy')->whereNumber('blog');
});

Route::resource('/sign-up', RegistrationController::class)->only([
    'index', 'store',
])->middleware('guest');

Route::prefix('/auth')->as('auth.')->group(function () {
    Route::redirect('/', '/auth/sign-in', 301);
    Route::get('/sign-in', [LoginController::class, 'index'])->name('sign-in.index')->middleware('guest');
    Route::post('/sign-in', [LoginController::class, 'store'])->name('sign-in.store')->middleware('guest');
});

Route::get('/sign-out', [LogOutController::class, 'index'])->name('sign-out.index')->middleware('auth');

Route::get('/forgot-password', [ForgotPasswordController::class, 'create'])->name('forgot-password.create')->middleware('guest');
Route::post('/forgot-password', [ForgotPasswordController::class, 'store'])->name('forgot-password.store')->middleware('guest');
Route::get('/reset-password', [ResetPasswordController::class, 'create'])->name('password.reset')->middleware('guest');

Route::prefix('/categories')->middleware('auth')->group(function () {
    Route::get('/', [CategoryController::class, 'index'])->name('categories.index');
    Route::get('/create', [CategoryController::class, 'create'])->name('categories.create');
    Route::post('/', [CategoryController::class, 'store'])->name('categories.store');
    Route::get('/{category}/edit', [CategoryController::class, 'edit'])->name('categories.edit');
    Route::patch('/{category}', [CategoryController::class, 'update'])->name('categories.update');
    Route::delete('/{category}', [CategoryController::class, 'destroy'])->name('categories.destroy');
});

Route::get('/users/{userId}', [UserController::class, 'show'])->name('users.show')->middleware('auth')->whereNumber('userId');
Route::get('/users/{userId}/edit', [UserController::class, 'edit'])->name('users.edit')->middleware('auth')->whereNumber('userId');
Route::patch('/{userId}', [UserController::class, 'update'])->name('users.update')->middleware('auth')->whereNumber('userId');

Route::fallback(function () {
    return Redirect::to('/');
}
);

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('page.title', config('app.name'))</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class='flex flex-col justify-between min-h-screen'>
    @include('layouts.header')
    <main class='flex-1	my-7 w-9/12	mx-auto'>
        @yield('content')
    </main>
    @include('layouts.footer')
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class='bg-gray-800'>
    <x-footer.footer-wrapper>
    {{ config('app.name') . ' ' . date('Y') }}
    </x-footer.footer-wrapper>
</footer>

resources/views/layouts/header.blade.php
<header>
    <x-header.header-navigation>
      <x-header.logo />
      <div class="hidden sm:ml-6 sm:block">
        <div class="flex space-x-4">
          @auth
            <x-header.navigation-link href="{{ route('blogs.index') }}">Blogs</x-header.navigation-link>
            <x-header.navigation-link href="{{ route('sign-out.index') }}">Sign Out</x-header.navigation-link>
          @endauth
          @guest
            <x-header.navigation-link href="{{ route('auth.sign-in.index') }}">Sign In</x-header.navigation-link>
            <x-header.navigation-link href="{{ route('sign-up.index') }}">Sign Up</x-header.navigation-link>
          @endguest
          </div>
      </div>
    </x-header.header-navigation>
  </header>